# Generated by Django 3.2.25 on 2025-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='08158216178', max_length=15),
        ),
    ]
