# Generated by Django 3.2.25 on 2025-08-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_auto_20250814_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
